language: python
sudo: false
python:
  - 2.7
  - 3.6
matrix:
    include:
      - python: 3.6
        name: "Flake8"
        install:  pip install -U flake8
        script: flake8 --doctests src setup.py
install:
  - pip install -U pip setuptools zope.testrunner
  - pip install -U coveralls coverage
  - python bootstrap.py
  - bin/buildout
  - pip install -U -e .
script:
  - coverage run -m zope.testrunner --test-path=src --auto-color
after_success:
  - coveralls
notifications:
  email: false
cache: pip
